steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/worksap-x-manuscript-199502/example', '-f', './app/Dockerfile']
images: ['asia.gcr.io/worksap-x-manuscript-199502/example']
